"""Initial database schema

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2024-05-28 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid # Required for default=uuid.uuid4

# revision identifiers, used by Alembic.
revision = '1a2b3c4d5e6f' # Kept the same as the target filename for this attempt
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('ticker', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('sector', sa.String(), nullable=True),
        sa.Column('industry', sa.String(), nullable=True),
        sa.Column('logo_url', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)

    op.create_table('fundamental_data',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('stock_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('pb_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('dividend_yield', sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column('eps', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column('last_updated', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stock_id')
    )

    op.create_table('news_articles',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('stock_id', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('source_name', sa.String(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('image_url', sa.String(), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=False),
        sa.Column('fetched_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)

    op.create_table('price_data',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('stock_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('open', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('high', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('low', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('close', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('volume', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('stock_id', 'date', name='uq_stock_date')
    )
    op.create_index(op.f('ix_price_data_date'), 'price_data', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_data_date'), table_name='price_data')
    op.drop_table('price_data')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_table('fundamental_data') 
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
